apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: management_app
type: Opaque
data:
  postgres-uri: bW9uZ29kYitzcnY6Ly9BZG1pbjphZG1pbjEyMzQ1NkBjbHVzdGVyMC51MXNtM2U0Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
